Attempt to fix CI UnknownHostException:
java.net.UnknownHostException: Unable to resolve host "http-inputs-inst.splunkcloud.com": No address associated with hostname

Probably the issue was that the device was offline when the test has failed so it cannot open the connection for the Splunk URL.